name: 构建移动端安装包

on:
  push:
    branches:
      - main

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: preview
  build_ios:
    type: build
    params:
      platform: ios
      profile: preview
